import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./components/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Netflix-clone",
  description: "Generated by create next app",
  applicationName: "Netflix-clone",
  icons: {
    icon: ["/netflix_logo.svg?v=4"],
    apple: ["/netflix_logo.svg?v=4"],
    shortcut: ["/netflix_logo.svg"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="iw">
      <body className={inter.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
